### ISSUE TITLE
Runtime exception with Streaming API

### ISSUE THREAD

**Issue by gohelkiran30** [advisors-excel-llc/salesforce-rest-sdk#74]
Getting this weird runtime exception error after about 60 seconds ....

```
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(https://nettix--uat.my.salesforce.com/cometd/48.0/meta/connect): failed to open stream: HTTP request failed!
[file] /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(334): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(51): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Middleware.php(36): GuzzleHttp\PrepareBodyMiddlew in /home/kiran/web/my-vehicles/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52

```

**Comment by C0chett0** [comment]
Same here !

**Comment by gohelkiran30** [comment]
Issue is fixed. This error was generated due to missing php-curl extension.
