### ISSUE TITLE
curl SSL certificate error

### ISSUE THREAD

**Issue by zinmyotun-gic** [advisors-excel-llc/salesforce-rest-sdk#85]
I have faced problem getting curl SSL certificate error CachedOAuthProvider and OAuthProvider when running from shell.
We should add options parameter for CachedOAuthProvider and OAuthProvider construct function.

Error: [GuzzleHttp\Exception\RequestException] cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201
#1 \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()

Stack Trace:
#0 \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 \vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 \vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 \vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 \vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 \vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 \vendor\guzzlehttp\guzzle\src\Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 \vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 \vendor\guzzlehttp\guzzle\src\Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 \vendor\guzzlehttp\guzzle\src\HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10　\vendor\guzzlehttp\guzzle\src\Client.php(351): GuzzleHttp\HandlerStack->__invoke()
#11　\vendor\guzzlehttp\guzzle\src\Client.php(162): GuzzleHttp\Client->transfer()
#12　\vendor\guzzlehttp\guzzle\src\Client.php(182): GuzzleHttp\Client->requestAsync()
#13　\vendor\guzzlehttp\guzzle\src\Client.php(95): GuzzleHttp\Client->request()
#14　\vendor\ae\salesforce-rest-sdk\src\AuthProvider\OAuthProvider.php(148): GuzzleHttp\Client->__call()
#15　\vendor\ae\salesforce-rest-sdk\src\Rest\Client.php(214): AE\SalesforceRestSdk\AuthProvider\OAuthProvider->authorize()
#16　\vendor\ae\salesforce-rest-sdk\src\Rest\Client.php(55): AE\SalesforceRestSdk\Rest\Client->createHttpClient()

**Comment by hanishsingla** [comment]
This error is related to your own machine environment. Here is the solution for it https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate
